### ISSUE TITLE
Not able to login using token

### ISSUE THREAD

**Issue by bluecification** [katant/HQApi#11]
I'm currently trying to run a file that only tries to delete avatar. I've been using the sample code, and I'm currently getting the error:

` File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/HQApi-1.8.1-py3.6.egg/HQApi/hq_api.py", line 52, in delete_avatar
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/HQApi-1.8.1-py3.6.egg/HQApi/hq_api.py", line 110, in fetch
HQApi.exceptions.ApiResponseError: {"error": "Auth not valid", "errorCode": 105}`

I'm fairly certain that this means that my token is the cause behind the error. I've tried using some of the other methods, and they don't work either for the same error. I've also used tokens from multiple accounts, and I'm still receiving the error. As far as I know, the only possible error from my end is that I might be somehow formatting the token wrong, but that wouldn't make sense because I'm copy-pasting it directly from the program. I know that the library is working properly at least because I'm able to successfully get the next show, as that doesn't require a bearer. Here's my code for setting the bearer as a string:

`bearer = "eyJhbGciOiJIUzI1NiIsIjR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE2NDq1NjUsInVzZXJuYW1lIjoiYW41MTYiLCJhdmF0YXJVcmwiOiJzMzovL2hmcGVzcGFjZS1xdWl6L2EvNDEvMTY0OTU2NS1obkxFSkwuanBnIiwidG9rZW4iOiJ5WmhTWEsiLCJyb2xlcyI6W10sImNsaWVuoCI6IiIsImd1ZXN0SWQiOm51bGwsIlYiOjEsImlhdCI6MTz0OTIxMTIwMSweZXhwIjoxNTU2OTg3MjAxLCJpc3MiOiJoeXBlcXVpei8xIn0.OB57yBa7RQ-zQnY3Q1n9zGikGgPEkKfX8vzZnCe3zsQ"`

I've obviously changed many of the letters, so that's not actually my bearer, but that's just an example of how mine is formatted. Any input would be great.

**Comment by katant** [comment]
Fixed in 1.8.2
