### ISSUE TITLE
The demo websocket website is down.

### ISSUE THREAD

**Issue by bluecification** [katant/HQApi#12]
I've been trying to work with the demo websocket in order to test some things, however, the demo site is currently down. I believe the address is hqecho.herokuapp.com, and when going to it, it says that an upgrade is required. The url for the websocket isn't working either, so I'm assuming that it's currently down. Is there another site I can use to conduct testing? Thanks. Also, I'd love to talk to you on Discord and contribute to this project, as I have a bit of Python experience. My Discord ID is Blue#2222. Thanks!

-Blue

**Comment by DataPools** [comment]
It's not currently down.
You can check using this: https://www.websocket.org/echo.html

**Comment by bluecification** [comment]
Hmm. It's down as I type this, here's a screenshot:
![image](https://user-images.githubusercontent.com/35982379/54090997-9e0eff00-4348-11e9-96f9-f360deaa607e.png)

Not sure if this was the same thing as earlier, but even from the website you provided to check, I am getting an error.

**Comment by Nothecaptain** [comment]
It is not down can confirm

**Comment by bluecification** [comment]
It *just* went back up.
