### ISSUE TITLE
Can't actually connect to the HQ websocket

### ISSUE THREAD

**Issue by bluecification** [katant/HQApi#13]
I've been working with the library a bit, and today I ran some real testing during a game. The websocket was working perfectly fine with the hqecho website, so I decided to run a few tests in a real game. I ran into an issue where the bot quite simply just didn't connect to the HQ websocket, which I found strange. I ran some tests and determined that I wasn't banned, so the only possible error is that it wasn't working with the websocket properly. Am I the only person who's run into this error?

**Comment by katant** [comment]
Are you running 1.9.0 or pip version?

**Comment by bluecification** [comment]
1.9.0

**Comment by bluecification** [comment]
Just wanted to bump this, as I'm still having issues connecting, and I've been using everything correctly.

**Comment by katant** [comment]
Try this example code and check output
`
import json
import re
from lomond.persist import persist
from HQApi import HQApi, HQWebSocket

bearer = "Bearer"
api = HQApi(bearer)
ws = HQWebSocket(api)
websocket = ws.get()

for msg in persist(websocket):
    print(str(msg))`
