### ISSUE TITLE
brodcastEnded hq words

### ISSUE THREAD

**Issue by romkacaddy** [katant/HQApi#14]
'reason': 'You are no longer in the game. Please join again.
why this error may occur.
I play with 50+ accounts.
kick before the game starts and after sending letters

**Comment by katant** [comment]
This is just HQ security from words bots, I can't say you method to bypass it, so just keep trying

**Comment by 12135555** [comment]
> This is just HQ security from words bots, I can't say you method to bypass it, so just keep trying

So you have found a way how to bypass it? Or is it impossible to bypass?
