### ISSUE TITLE
Eraser Support

### ISSUE THREAD

**Issue by nununoisy** [katant/HQApi#2]
This API still doesn't support the "new" power up. If I found some time, I might be able to open a PR...

**Comment by nununoisy** [comment]
So erasers run through comments? Seems very hacky (then again, seems right). Do you have any idea how that works?

**Comment by nununoisy** [comment]
What would be even better is if we had a huge websocket dump from a live game. I'm on an iPhone and can't intercept the packets.

**Comment by katant** [comment]
Not erasers thought comments, just new method

**Comment by DataPools** [comment]
JSON to get erasers:
```{
    "authToken": authToken,
    "friendsIds": [123, 456],
    "broadcastId": broadcastId,
    "type": "erase1Earned"
}```
JSON to erase an answer during the game:
```{"type": "erase1", "questionId": questionId, "authToken": authToken, "broadcastId": broadcastId}```

**Comment by katant** [comment]
Added on 1.7.0
