### ISSUE TITLE
Hq Swipe Trick

### ISSUE THREAD

**Issue by MaheshMahi19** [katant/HQApi#3]
What is the api/websocket for HQ's Swipe Trick.? For having an extra Life

**Comment by nununoisy** [comment]
HQApi.easter_egg

**Comment by nununoisy** [comment]
If you import the class it should be there

```python
from HQApi import HQApi
// Add bearer token
HQApi.easter_egg()
```

**Comment by katant** [comment]
HQ changed easter egg, so this method is outdated
