### ISSUE TITLE
More detailed documentation

### ISSUE THREAD

**Issue by nununoisy** [katant/HQApi#4]
The methods give a basic idea of how some functions work, but a lot of this implementation is a black box. With some time, we could find some return values and other data and compile a wiki.

**Comment by nununoisy** [comment]
For example, when trying to use `send_code`, all I get is an error message: 
```js
{ error: 'That phone number is invalid.', errorCode: 451 }
```

What is a valid phone number format?

**Comment by katant** [comment]
Fixed
