### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Almancat10** [katant/HQApi#6]
Add me on discord @Nutella#6019 I would like to contact you about something.
Thanks

**Comment by Almancat10** [comment]
The error I got when trying to cashout money from my account to my PayPal account was:

And I got this error not sure why:

HQApi.exceptions.ApiResponseError: {"error": "Auth not valid", "errorCode": 105}

**Comment by Almancat10** [comment]
Not sure why, both my PayPal email and bearer token are valid and my HQ account has a balance above 0.

**Comment by Almancat10** [comment]
I believe this has to be something with how HQ updated their cashout system in their most recent update of the app: version 1.4.5

**Comment by katant** [comment]
Fix
