### ISSUE TITLE
region error 

### ISSUE THREAD

**Issue by NirwanTech** [katant/HQApi#8]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    ws = HQWebSocket(api)
  File "/home/runner/HQApi/hq_websocket.py", line 12, in __init__
    self.region = HQApi.api(api).region
AttributeError: 'HQApi' object has no attribute 'region'


**Comment by Nothecaptain** [comment]
Why do you need this dont you already have hq bot?

**Comment by NirwanTech** [comment]
I know but I need to cash out money!
As well as want to create a Websocket bot

Please help me if ur my subscriber!

**Comment by Nothecaptain** [comment]
First of all I am not a subscriber 
Second even if I was i would have no clue what to do and i highly suggest just to search your issue beforehand.Im assuming you arent using a rewrite of python try thar first.

**Comment by NirwanTech** [comment]
see same error again see ss
https://imgur.com/qIb75Yx

**Comment by NirwanTech** [comment]
Please Help Me God will help you!🙏

**Comment by nununoisy** [comment]
This might be a larger issue - [version 1.6.0](
https://github.com/katant/HQApi/commit/592be363c5ae9b0ca59676a0352bbe509b54c522) removed regions but there are still references to them throughout the code. I found two old references: `hq_websocket.py` line 12, and `hq_api.py` line 45. Removal might not be straightforward here. @katant, what should we do: remove regions from request headers, assume a default region, or create getter/setter functions for the region?

**Comment by katant** [comment]
Completely fix in 1.7.2
