### ISSUE TITLE
WebSocket documentation/dumps

### ISSUE THREAD

**Issue by nununoisy** [katant/HQApi#9]
The documentation for this API is still lacking as HQ's servers are a black box. If someone has a large dump of the websocket for Trivia or Words it would be super helpful to write some documentation on HQ's API responses.

So far I've only found old dumps of Trivia's websocket that don't have new features like erasers, and I couldn't find anything for Words.

**Comment by Nothecaptain** [comment]
Im guessing you are trying to make an emulator or answerer for hq.

**Comment by nununoisy** [comment]
Something like that, or just a more complete API. I don't think there'll be any issues with bot makers since you still need a bearer token. It would also enable us to add events to the WebSocket API, like onQuestion, onWordsWheel, etc.

**Comment by Nothecaptain** [comment]
Ill be more then happy to help if i knew how to get a websocket dump from hq haha.I can try and get some responses with some mitm programs if that helps

**Comment by nununoisy** [comment]
Thanks. I would do it myself but I have an iPhone and no way to use mitm myself. All I can snoop on is the HTTP side of the api.

**Comment by Nothecaptain** [comment]
Ive been trying to make my own bot but havent gotten far haha.If you are up to it maybe we can collab on the project or something

**Comment by nununoisy** [comment]
Sure. If I can get my hands on a comprehensive dump I'll write the documentation and maybe even code to make it more friendly.

**Comment by Nothecaptain** [comment]
What wpuld you guys suggest for capturing dumps?

**Comment by katant** [comment]
Since hq is now ssl pinning websocket, I think that on android this is definitely impossible without mirror server HQ Trivia, which logs everything

**Comment by Nothecaptain** [comment]
I own multiple android devices as I am an android user but im talking about program wise if there are any programs in specific you would recommend . Or if you are just looking to capture the traffic .I use mitm proxy but im open to suggestions

**Comment by katant** [comment]
If you need to capture REST API, try Charles, Fiddler, mitmproxy or anything what you like, with xposed and SSLUnpinning 2.0 module to bypass ssl pinning (this method also works with HQ)

**Comment by Nothecaptain** [comment]
I use a combination of mitm + ssl unpinner 2.0 so ill try and capture the traffic for the 3pm game

**Comment by katant** [comment]
As I said before, HQ is now pinning web socket, which is impossible to unpin via ssl unpinning 2.0

**Comment by Nothecaptain** [comment]
Impossible or possible i dont understand

**Comment by katant** [comment]
Just REST API possible to sniff

**Comment by nununoisy** [comment]
Perhaps we could use a [Frida Gadget](
https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/) to disable SSL pinning. You grab an HQ APK and inject the gadget into it. Then using the command line, we can disable pinning. If we use this alongside a mitm proxy like Charles or Burp, we might be able to get the dump.

**Comment by nununoisy** [comment]
If we did do a dump, it would be helpful if during the game we document things we haven't documented yet. For Trivia:

+ Streak time
+ HQ Words/Sports subscribe button
+ Extra life pop ups
+ Eraser (server response)
+ Use a life
+ Free Passes/Points/Level up
+ Interaction

For Words:
+ Wheel letter choices
+ Using a life
+ Strikes per game
+ Interaction (e.g. live answer stats)

**Comment by Nothecaptain** [comment]
Frida may take some time as i have never been successful with it in the past maybe with my better knowledge now i can try it again

**Comment by Nothecaptain** [comment]
You guys use discord? My tag is NotheCaptain#0001 maybe we can continue this there

**Comment by Nothecaptain** [comment]
I talked to katant and he said he tried just about everything (I know at least) to get the hq info but nothing seems to work out I think we should close this on the count of hq putting that ssl pinner in place.If anyone knows anything more feel free to dm or add on I think I dont have much else to say.

**Comment by Nothecaptain** [comment]
Or keep this open just incase someone taks something onto here one day

**Comment by nununoisy** [comment]
@katant, does the HQ app use the system-provided SSL pinning or does it use further verification? If we can't reverse-engineer the app, I'll make a burner account and try to play a game with the info we already know.

**Comment by MaheshMahi19** [comment]
To get an eraser How do i send friendIds to respective function..

**Comment by katant** [comment]
> To get an eraser How do i send friendIds to respective function..

List with two int userids

**Comment by DataPools** [comment]
I actually wrote a script to modify the app so that it can connect to my mirror server without SSL pinning.

Here are my game dumps: https://0bin.net/paste/EJ27Ovtc-XDu3O-m#e-JdcvYKZCZfHNnrKHyP+Z5AdgtXVk92lIbGMpkqQdQ

**Comment by Nothecaptain** [comment]
Thats only a dump of the rest api
Not what we wanted

**Comment by DataPools** [comment]
@Nothecaptain That is a websocket dump.

**Comment by Nothecaptain** [comment]
Yes it is.But It doesnt contain the information we need.I can get the exact same dump from my own phone and computer

**Comment by Nothecaptain** [comment]
I do thank you for the contribution otherwise.Its nice to know some people are willing to help :).

**Comment by nununoisy** [comment]
@DataPools, could you provide your patched app so I can do some more experimentation?

**Comment by DataPools** [comment]
Here's the download for the patched APK:
https://my.mixtape.moe/fgntkk.apk

**Comment by MaheshMahi19** [comment]
Does it work out of SSL pinning..

**Comment by katant** [comment]
New 1.12 release has log system and now we can log all messages with unknown types. Works only with new event system

**Comment by geosonic** [comment]
Your all stupid xD
